source "https://rubygems.org"

gemspec

# Use the local patient_http checkout when present so the gems can be
# developed in tandem before a release.
local_patient_http = File.expand_path("../patient_http", __dir__)
if File.directory?(local_patient_http)
  gem "patient_http", path: local_patient_http
end

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "protocol-rack"
  gem "webmock", "~> 3.26"
  gem "async-rspec", "~> 1.17"
  gem "rack-test", "~> 2.1", require: false
  gem "irb"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false
  end
end
