source "https://rubygems.org"

gemspec path: ".."

gem "protocol-rack"
gem "rack-session"
gem "sidekiq-encrypted_args"
gem "irb"

gem "async_http_pool", github: "bdurand/async_http_pool", branch: "main"
